import Head from "next/head";
import Link from "next/link";
import Cards from "../components/Cards/Cards";
import Typography from "../components/Typography/Typography";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant="h1" className={styles.title}>
        Welcome to <Link href="/">Next-Weather!</Link>
      </Typography>

      <Typography
        variant="subtitle1"
        align="center"
        className={styles.description}
      >
        Get started by editing{" "}
        <code className={styles.code}>pages/index.tsx</code>
      </Typography>

      <Cards>
        <Cards.Card href="login" title="Connexion">
          <p>Connectez-vous pour récupérer vos préférences</p>
        </Cards.Card>
        <Cards.Card href="register" title="Inscription">
          <p>Inscrivez-vous pour synchroniser vos préférences</p>
        </Cards.Card>
      </Cards>

      <Typography variant="body1" align="center">
        Utiliser Next-Weather <Link href="home">sans compte</Link>.
      </Typography>
    </div>
  );
};

export default Home;
